services:
  - type: web
    name: proyecto-glosas-cp
    runtime: python
    buildCommand: pip install -r dashboard/requirements.txt
    startCommand: python dashboard/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
